// Reexporta os componentes comuns para facilitar os imports nas paginas.
export { default as GlassCard } from './CartaoVidro'
export { default as SummaryCard } from './CartaoResumo'
export { default as PageHeader } from './CabecalhoPagina'
export { default as MoneyValue } from './ValorMonetario'
export { default as Icon } from './Icone'
export { default as EmptyState } from './EstadoVazio'
export { default as ConfirmDialog } from './DialogoConfirmacao'
export { default as StatusBadge } from './SeloStatus'
export { default as ChartContainer } from './ContainerGrafico'
export { default as FormField } from './CampoFormulario'
export { default as LoadingScreen } from './TelaCarregando'
export { default as PrivateRoute } from './RotaPrivada'
export { default as ErrorBoundary } from './LimiteErro'
export { default as Toast, toast, setGlobalToastRef } from './Notificacao'
